package com.khanh.fooddelivery.restaurant_service.controller;
import com.khanh.fooddelivery.restaurant_service.common.response.ApiResponse; import com.khanh.fooddelivery.restaurant_service.dto.request.*; import com.khanh.fooddelivery.restaurant_service.dto.response.*; import com.khanh.fooddelivery.restaurant_service.service.RestaurantApplicationService; import jakarta.validation.Valid; import lombok.RequiredArgsConstructor; import org.springframework.data.domain.*; import org.springframework.data.web.PageableDefault; import org.springframework.http.*; import org.springframework.security.access.prepost.PreAuthorize; import org.springframework.security.core.Authentication; import org.springframework.security.core.annotation.AuthenticationPrincipal; import org.springframework.security.oauth2.jwt.Jwt; import org.springframework.web.bind.annotation.*; import java.util.*;
@RestController @RequestMapping("/api/v1/restaurant-applications") @RequiredArgsConstructor public class RestaurantApplicationController {private final RestaurantApplicationService service;
 @PostMapping public ResponseEntity<ApiResponse<RestaurantApplicationResponse>> create(@AuthenticationPrincipal Jwt jwt,@Valid @RequestBody RestaurantApplicationCreateRequest r){return ResponseEntity.status(HttpStatus.CREATED).body(ApiResponse.success("Restaurant application created successfully",service.create(jwt,r)));}
 @GetMapping("/me") public ApiResponse<List<RestaurantApplicationSummaryResponse>> mine(@AuthenticationPrincipal Jwt jwt){return ApiResponse.success("Restaurant applications retrieved successfully",service.mine(jwt));}
 @GetMapping("/{id}") public ApiResponse<RestaurantApplicationResponse> get(@AuthenticationPrincipal Jwt jwt,Authentication a,@PathVariable UUID id){return ApiResponse.success("Restaurant application retrieved successfully",service.get(jwt,id,isAdmin(a)));}
 @GetMapping @PreAuthorize("hasAnyRole('ADMIN','SUPPORT')") public ApiResponse<Page<RestaurantApplicationSummaryResponse>> all(@PageableDefault(size=20,sort="createdAt",direction=Sort.Direction.DESC) Pageable p){return ApiResponse.success("Restaurant applications retrieved successfully",service.all(p));}
 @PatchMapping("/{id}") public ApiResponse<RestaurantApplicationResponse> update(@AuthenticationPrincipal Jwt jwt,@PathVariable UUID id,@Valid @RequestBody RestaurantApplicationUpdateRequest r){return ApiResponse.success("Restaurant application updated successfully",service.update(jwt,id,r));}
 @PostMapping("/{id}/submit") public ApiResponse<RestaurantApplicationResponse> submit(@AuthenticationPrincipal Jwt jwt,@PathVariable UUID id){return ApiResponse.success("Restaurant application submitted successfully",service.submit(jwt,id));}
 @PostMapping("/{id}/cancel") public ApiResponse<RestaurantApplicationResponse> cancel(@AuthenticationPrincipal Jwt jwt,@PathVariable UUID id){return ApiResponse.success("Restaurant application cancelled successfully",service.cancel(jwt,id));}
 @PostMapping("/{id}/start-review") @PreAuthorize("hasAnyRole('ADMIN','SUPPORT')") public ApiResponse<RestaurantApplicationResponse> review(@AuthenticationPrincipal Jwt jwt,@PathVariable UUID id){return ApiResponse.success("Application review started",service.startReview(jwt,id));}
 @PostMapping("/{id}/request-information") @PreAuthorize("hasAnyRole('ADMIN','SUPPORT')") public ApiResponse<RestaurantApplicationResponse> info(@AuthenticationPrincipal Jwt jwt,@PathVariable UUID id,@Valid @RequestBody ApplicationInformationRequest r){return ApiResponse.success("Additional information requested",service.requestInformation(jwt,id,r));}
 @PostMapping("/{id}/approve") @PreAuthorize("hasAnyRole('ADMIN','SUPPORT')") public ApiResponse<RestaurantResponse> approve(@AuthenticationPrincipal Jwt jwt,@PathVariable UUID id){return ApiResponse.success("Restaurant application approved successfully",service.approve(jwt,id));}
 @PostMapping("/{id}/reject") @PreAuthorize("hasAnyRole('ADMIN','SUPPORT')") public ApiResponse<RestaurantApplicationResponse> reject(@AuthenticationPrincipal Jwt jwt,@PathVariable UUID id,@Valid @RequestBody ApplicationRejectionRequest r){return ApiResponse.success("Restaurant application rejected",service.reject(jwt,id,r));}
 @PostMapping("/{id}/documents") public ResponseEntity<ApiResponse<ApplicationDocumentResponse>> addDocument(@AuthenticationPrincipal Jwt jwt,@PathVariable UUID id,@Valid @RequestBody ApplicationDocumentCreateRequest r){return ResponseEntity.status(HttpStatus.CREATED).body(ApiResponse.success("Application document created successfully",service.addDocument(jwt,id,r)));}
 @GetMapping("/{id}/documents") public ApiResponse<List<ApplicationDocumentResponse>> documents(@AuthenticationPrincipal Jwt jwt,Authentication a,@PathVariable UUID id){return ApiResponse.success("Application documents retrieved successfully",service.documents(jwt,id,isAdmin(a)));}
 @DeleteMapping("/{id}/documents/{documentId}") public ApiResponse<Void> deleteDocument(@AuthenticationPrincipal Jwt jwt,@PathVariable UUID id,@PathVariable UUID documentId){service.deleteDocument(jwt,id,documentId);return ApiResponse.success("Application document deleted successfully");}
 @PostMapping("/{id}/documents/{documentId}/verify") @PreAuthorize("hasAnyRole('ADMIN','SUPPORT')") public ApiResponse<ApplicationDocumentResponse> verify(@AuthenticationPrincipal Jwt jwt,@PathVariable UUID id,@PathVariable UUID documentId){return ApiResponse.success("Application document verified",service.verifyDocument(jwt,id,documentId));}
 @PostMapping("/{id}/documents/{documentId}/reject") @PreAuthorize("hasAnyRole('ADMIN','SUPPORT')") public ApiResponse<ApplicationDocumentResponse> rejectDocument(@AuthenticationPrincipal Jwt jwt,@PathVariable UUID id,@PathVariable UUID documentId,@Valid @RequestBody ApplicationDocumentVerificationRequest r){return ApiResponse.success("Application document rejected",service.rejectDocument(jwt,id,documentId,r));}
 private boolean isAdmin(Authentication a){return a.getAuthorities().stream().anyMatch(x->x.getAuthority().equals("ROLE_ADMIN")||x.getAuthority().equals("ROLE_SUPPORT"));}}
