services:
  postgres:
    image: postgres:17
    container_name: food-delivery-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./infrastructure/postgres/init:/docker-entrypoint-initdb.d
    networks:
      - food-delivery-network

  keycloak:
    image: quay.io/keycloak/keycloak:26.6.4
    container_name: food-delivery-keycloak
    environment:
      KC_BOOTSTRAP_ADMIN_USERNAME: ${KEYCLOAK_ADMIN}
      KC_BOOTSTRAP_ADMIN_PASSWORD: ${KEYCLOAK_ADMIN_PASSWORD}

      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://postgres:5432/keycloak_db
      KC_DB_USERNAME: postgres
      KC_DB_PASSWORD: postgres

      KC_HEALTH_ENABLED: "true"
      KC_METRICS_ENABLED: "true"
    command:
      - start-dev
      - --import-realm
    ports:
      - "${KEYCLOAK_PORT}:8080"
    volumes:
      - ./infrastructure/keycloak/realms:/opt/keycloak/data/import
    depends_on:
      - postgres
    networks:
      - food-delivery-network

volumes:
  postgres_data:

networks:
  food-delivery-network:
    driver: bridge
