package com.khanh.fooddelivery.payment_service.model;

public enum LedgerEntryType {
    CUSTOMER_PAYMENT_CAPTURED,
    DRIVER_RESTAURANT_ADVANCE,
    DRIVER_CUSTOMER_CASH_COLLECTED,
    RESTAURANT_PAYABLE_CREATED,
    DRIVER_PAYABLE_CREATED,
    RESTAURANT_COMMISSION_RECEIVABLE,
    DRIVER_COMMISSION_RECEIVABLE,
    PLATFORM_REVENUE_RECOGNIZED,
    CUSTOMER_REFUND,
    RESTAURANT_PAYABLE_REVERSAL,
    DRIVER_PAYABLE_REVERSAL,
    PLATFORM_REVENUE_REVERSAL,
    RESTAURANT_PAYOUT,
    DRIVER_PAYOUT,
    COMMISSION_SETTLED
}
