package com.khanh.fooddelivery.search_service.event;

public enum CatalogEventType {
    CATALOG_ITEM_UPSERTED,
    CATALOG_ITEM_STATUS_CHANGED,
    BRANCH_ITEM_UPSERTED,
    BRANCH_ITEM_PRICE_CHANGED,
    BRANCH_ITEM_AVAILABILITY_CHANGED,
    MENU_CHANGED,
    MENU_CATEGORY_CHANGED,
    MENU_CATEGORY_ITEM_CHANGED,
    OPTION_GROUP_CHANGED,
    OPTION_VALUE_CHANGED
}
