package com.khanh.fooddelivery.driver_service.controller;
import com.khanh.fooddelivery.driver_service.entity.DriverAvailability; import com.khanh.fooddelivery.driver_service.repository.DriverAvailabilityRepository; import java.util.*; import lombok.RequiredArgsConstructor; import org.springframework.security.core.annotation.AuthenticationPrincipal; import org.springframework.security.oauth2.jwt.Jwt; import org.springframework.transaction.annotation.Transactional; import org.springframework.web.bind.annotation.*;
@RestController @RequiredArgsConstructor public class DriverAvailabilityController { private final DriverAvailabilityRepository drivers;
 @PutMapping("/api/v1/drivers/me/availability") @Transactional public DriverAvailability set(@AuthenticationPrincipal Jwt jwt,@RequestBody AvailabilityRequest r){ UUID user=user(jwt); DriverAvailability d=drivers.findByUserId(user).orElseGet(()->{DriverAvailability x=new DriverAvailability();x.setId(UUID.randomUUID());x.setUserId(user);return x;}); if(d.getActiveDeliveryId()!=null&&r.available()) throw new IllegalStateException("Driver has active delivery");d.setAvailable(r.available());return drivers.save(d); }
 @GetMapping("/internal/v1/drivers/available") public List<UUID> available(){return drivers.findTop10ByAvailableTrueAndActiveDeliveryIdIsNullOrderByUpdatedAtAsc().stream().map(DriverAvailability::getUserId).toList();}
 @PostMapping("/internal/v1/drivers/{driverId}/reserve/{deliveryId}") @Transactional public void reserve(@PathVariable UUID driverId,@PathVariable UUID deliveryId){DriverAvailability d=drivers.findByUserId(driverId).orElseThrow();if(!d.isAvailable()||d.getActiveDeliveryId()!=null)throw new IllegalStateException("Driver unavailable");d.setActiveDeliveryId(deliveryId);d.setAvailable(false);}
 @PostMapping("/internal/v1/drivers/{driverId}/release/{deliveryId}") @Transactional public void release(@PathVariable UUID driverId,@PathVariable UUID deliveryId){drivers.findByUserId(driverId).filter(d->deliveryId.equals(d.getActiveDeliveryId())).ifPresent(d->{d.setActiveDeliveryId(null);d.setAvailable(true);});}
 private UUID user(Jwt jwt){String v=jwt.getClaimAsString("user_id");return UUID.fromString(v==null?jwt.getSubject():v);} public record AvailabilityRequest(boolean available){}
}
