import { type FormEvent, useEffect, useState } from 'react'
import { DeliveryLocationPicker } from '../../delivery/components/DeliveryLocationPicker'
import type { ReverseGeocodeCandidate } from '../../delivery/types/delivery'
import type { AddressCreateInput, AddressLabelType, AddressUpdateInput, DeliveryAddress } from '../types/address'

interface Props { address?: DeliveryAddress | null; submitting: boolean; submitError: string | null; onSubmit: (input: AddressCreateInput | AddressUpdateInput) => Promise<void>; onCancel: () => void }
interface Values { labelType: AddressLabelType; customLabel: string; recipientName: string; recipientPhone: string; addressLine: string; ward: string; district: string; city: string; buildingName: string; floor: string; entrance: string; deliveryNote: string; isDefault: boolean }
const empty: Values = { labelType: 'HOME', customLabel: '', recipientName: '', recipientPhone: '', addressLine: '', ward: '', district: '', city: '', buildingName: '', floor: '', entrance: '', deliveryNote: '', isDefault: false }
const text = (value: string) => value.trim() || undefined
const valuesOf = (address?: DeliveryAddress | null): Values => address ? { labelType: address.labelType, customLabel: address.customLabel ?? '', recipientName: address.recipientName, recipientPhone: address.recipientPhone, addressLine: address.addressLine, ward: address.ward ?? '', district: address.district ?? '', city: address.city ?? '', buildingName: address.buildingName ?? '', floor: address.floor ?? '', entrance: address.entrance ?? '', deliveryNote: address.deliveryNote ?? '', isDefault: address.isDefault } : empty
const locationOf = (address?: DeliveryAddress | null): ReverseGeocodeCandidate | null => address?.latitude !== null && address?.latitude !== undefined && address.longitude !== null && address.longitude !== undefined ? { formattedAddress: address.addressLine, addressLine: address.addressLine, ward: address.ward, district: address.district, city: address.city, latitude: address.latitude, longitude: address.longitude } : null

export function AddressForm({ address, submitting, submitError, onSubmit, onCancel }: Props) {
  const [values, setValues] = useState<Values>(() => valuesOf(address))
  const [location, setLocation] = useState<ReverseGeocodeCandidate | null>(() => locationOf(address))
  const [pickerOpen, setPickerOpen] = useState(false)
  const [formError, setFormError] = useState<string | null>(null)
  useEffect(() => { setValues(valuesOf(address)); setLocation(locationOf(address)); setFormError(null) }, [address])
  const change = (name: keyof Values, value: string | boolean) => setValues((current) => ({ ...current, [name]: value, ...(name === 'labelType' && value !== 'OTHER' ? { customLabel: '' } : {}) }))
  const receiveLocation = (next: ReverseGeocodeCandidate) => { setLocation(next); setValues((current) => ({ ...current, addressLine: next.addressLine ?? next.formattedAddress, ward: next.ward ?? '', district: next.district ?? '', city: next.city ?? '' })); setPickerOpen(false) }
  const submit = async (event: FormEvent<HTMLFormElement>) => {
    event.preventDefault()
    if (!values.recipientName.trim() || !values.recipientPhone.trim()) { setFormError('Vui lòng điền tên và số điện thoại người nhận.'); return }
    if (values.labelType === 'OTHER' && !values.customLabel.trim()) { setFormError('Vui lòng nhập tên nhãn địa chỉ.'); return }
    if (!location) { setFormError('Vui lòng chọn và xác nhận vị trí giao hàng trên bản đồ.'); return }
    setFormError(null)
    const base = { labelType: values.labelType, customLabel: values.labelType === 'OTHER' ? text(values.customLabel) : undefined, recipientName: values.recipientName.trim(), recipientPhone: values.recipientPhone.trim(), addressLine: values.addressLine.trim(), ward: text(values.ward), district: text(values.district), city: text(values.city), latitude: location.latitude, longitude: location.longitude, buildingName: text(values.buildingName), floor: text(values.floor), entrance: text(values.entrance), deliveryNote: text(values.deliveryNote) }
    if (address) { await onSubmit(base as AddressUpdateInput); return }
    await onSubmit({ ...base, isDefault: values.isDefault })
  }
  return <><form className="address-form" onSubmit={(event) => void submit(event)} noValidate>
    <section className="form-section"><h3 className="form-section-title">Thông tin người nhận</h3><div className="form-grid two-columns"><label>Tên người nhận <span aria-hidden="true">*</span><input value={values.recipientName} onChange={(event) => change('recipientName', event.target.value)} maxLength={255} required autoComplete="name" /></label><label>Số điện thoại <span aria-hidden="true">*</span><input value={values.recipientPhone} onChange={(event) => change('recipientPhone', event.target.value)} maxLength={20} required inputMode="tel" autoComplete="tel" /></label></div></section>
    <section className="form-section"><h3 className="form-section-title">Địa chỉ giao hàng</h3><fieldset className="address-label-options"><legend>Loại địa chỉ <span aria-hidden="true">*</span></legend><div className="address-label-choices">{(['HOME', 'WORK', 'OTHER'] as AddressLabelType[]).map((labelType) => <label key={labelType} className={values.labelType === labelType ? 'selected' : ''}><input type="radio" name="labelType" checked={values.labelType === labelType} onChange={() => change('labelType', labelType)} />{labelType === 'HOME' ? 'Nhà' : labelType === 'WORK' ? 'Công ty' : 'Khác'}</label>)}</div></fieldset>{values.labelType === 'OTHER' && <label>Tên địa chỉ <span aria-hidden="true">*</span><input value={values.customLabel} onChange={(event) => change('customLabel', event.target.value)} maxLength={100} placeholder="Ví dụ: Nhà bố mẹ" /></label>}
      <div className="address-location-picker-field"><div><strong>{location?.formattedAddress ?? 'Chưa chọn vị trí giao hàng'}</strong><small>{location ? 'Vị trí đã được xác nhận trên bản đồ' : 'Chọn vị trí để tính phí giao hàng chính xác'}</small></div><button type="button" className="button secondary" onClick={() => setPickerOpen(true)}>{location ? 'Đổi vị trí' : 'Chọn trên bản đồ'}</button></div>
    </section>
    <section className="form-section"><h3 className="form-section-title">Hướng dẫn giao hàng</h3><p className="form-section-hint">Các thông tin này giúp tài xế tìm bạn dễ hơn.</p><div className="form-grid three-columns"><label>Tòa nhà (không bắt buộc)<input value={values.buildingName} onChange={(event) => change('buildingName', event.target.value)} maxLength={255} /></label><label>Tầng (không bắt buộc)<input value={values.floor} onChange={(event) => change('floor', event.target.value)} maxLength={100} /></label><label>Cổng / lối vào (không bắt buộc)<input value={values.entrance} onChange={(event) => change('entrance', event.target.value)} maxLength={255} /></label></div><label>Ghi chú giao hàng (không bắt buộc)<textarea value={values.deliveryNote} onChange={(event) => change('deliveryNote', event.target.value)} maxLength={500} rows={3} placeholder="Ví dụ: Để tại lễ tân, gọi trước khi giao" /></label>{!address && <label className="checkbox-label"><input type="checkbox" checked={values.isDefault} onChange={(event) => change('isDefault', event.target.checked)} />Đặt làm địa chỉ mặc định</label>}</section>
    {(formError || submitError) && <p className="form-error" role="alert">{formError ?? submitError}</p>}<div className="form-actions"><button type="button" className="button secondary" onClick={onCancel} disabled={submitting}>Hủy</button><button type="submit" className="button primary" disabled={submitting}>{submitting ? 'Đang lưu…' : address ? 'Lưu thay đổi' : 'Thêm địa chỉ'}</button></div>
  </form>{pickerOpen && <DeliveryLocationPicker initialLocation={location} onConfirm={receiveLocation} onClose={() => setPickerOpen(false)} />}</>
}
